### PR TITLE
GDI+ dependencies to get MonoGame app SteamOS certified

### PR DESCRIPTION
**Pull request by ThomasFOG**
Here are the Linux dependencies for MonoGame. They all are related to GDI+...

Even though most of them are common in most distro's, they are missing from the Steam runtime and Valve requires any missing libraries to be shipped with games in order to have the "SteamOS certified" badge on the game page.

Ping @dellis1972 :)

### CODE REVIEW

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy ?

**Comment by dellis1972** [comment]
looks ok to me. @mrhelmut are you planning to get the OSX ones too? The will need the install_name_tool run on them to fix up the paths

```
#change path of another library
install_name_tool -change @executable_path/libpng14.14.dylib @loader_path/libpng14.14.dylib libfreetype.6.dylib
#change id of actual library
install_name_tool -id "@loader_path/libfreetype.6.dylib" libfreetype.6.dylib
```

**Comment by dellis1972** [comment]
can't remember to @loader_path is better than @executable_path

**Comment by harry-cpp** [comment]
Seems right to me, I really wish to remove System.Drawing as a dependency...

**Comment by dellis1972** [comment]
Well the MINIMAL build of OpenTK does not have System.Drawing .. but that means you can't set the window icon any more :(

**Comment by harry-cpp** [comment]
> Well the MINIMAL build of OpenTK does not have System.Drawing .. but that means you can't set the window icon any more :(

With SDL we should be able to load it without System.Drawing, `SDL_SetWindowIcon` :D

**Comment by ThomasFOG** [comment]
@dellis1972 GDI+ dependencies for OS X are already merged. Do they need something else?

Getting rid of `System.Drawing` would definitely be awesome, because it would make this repo useless and we could simply link to Ethan's fork.

**Comment by endimilojkoski** [comment]
I can confirm that after adding these libs the game is working fine for all with Arch Linux (they could not start it at all before these).
There are some minor issues reported:

Arch Linux user 1:
- Game starts in window mode even if last exited in fullscreen
- Screen goes black after 10 minutes when using a gamepad - game doesn't disable the screensaver
- Gamepad goes haywire if using the directional pad - works fine if using joystick only. But accidently pressing the d-pad messes up the joystick as well. It's like pressing down presses both down and right and that pressing up presses both up and left. Note: I'm using a PS4 controller (dualshock 4)

Linux user 2:
-Game runs great but using the dpad (Left trackpad) of the Steam controller goes nuts when i try to use it.

**Comment by ThomasFOG** [comment]
> Gamepad goes haywire if using the directional pad - works fine if using joystick only. But accidently pressing the d-pad messes up the joystick as well. It's like pressing down presses both down and right and that pressing up presses both up and left. Note: I'm using a PS4 controller (dualshock 4)

I fixed this issue on Windows, I know where's the problem is, I'll take a look (it's within OpenTK non-SDL2 Linux driver).

Steam controller will most probably require a custom config file (I think it should be removed from OpenTK, its configuration is supposed to be done within steamworks, though I don't know if that applies to non-Windows platforms). I haven't tried the Steam controller yet, but there's a documentation about how to get it natively working for your game on steamworks. You may be more advanced than me on that matter.

**Comment by endimilojkoski** [comment]
Not a big issue @mrhelmut just reporting it.
Since @cra0zy is working on SDL2 version of MonoGame it might solve all the issues so I will give that one a try soon.

**Comment by ThomasFOG** [comment]
OpenTK is going to be updated soon, so if I can slip in a few more fixes until it is completely removed...

**Comment by dellis1972** [comment]
@mrhelmut gonna merge these. 

Can you check the OS X binaries please. I just committed a change which changed the bathing using install_name_tool they work fine for me, just need someone to confirm.

**Comment by dellis1972** [comment]
bathing = pathing  btw... :)

**Comment by ThomasFOG** [comment]
I'll check that! :)

**Pull request merged**
