### PR TITLE
Updating SDL2

### PR DESCRIPTION
**Pull request by ThomasFOG**
This a SDL2 binaries update to the latest stable. For some reason it was missing `SDL_GetGlobalMouseState` (pretty sure it already was on 2.0.4).

Ping @dellis1972 :)

### CODE REVIEW

**Comment by dellis1972** [comment]
@mrhelmut is there a new windows binary?

**Comment by ThomasFOG** [comment]
Yes, but if I remember well, it is still unclear if SDL2.dll should be added to the template (since it's optional to have it, and that would force the SDL2 backend on windows). I think it's safer to leave it be while OpenTK is being replaced.

That reminds me another ongoing discussion: should openal32.dll be added to the DesktopGL template or not? mono/MonoGame#4329

**Comment by dellis1972** [comment]
@mrhelmut do we still need this?

**Comment by ThomasFOG** [comment]
No, it's outdated, I'm closing it! I will do a proper update very soon to match the latest changes and pull the latest bin from upstream.

**Pull request closed without merging**
